-- Meeting module: Meeting, AudioChunk, Speaker, SpeakerMapping,
-- TranscriptSegment, Bookmark, MeetingSummary + its child entities
-- (Topic, Decision, ActionItem, Blocker, OpenQuestion).
-- See Meeting schema documentation for the feature this backs.
-- Hand-written (not generated by `prisma migrate dev`) because the local dev
-- database has pre-existing, unrelated drift (a mindmap_chat_sessions column
-- applied outside the migrations directory) that blocks introspection-based
-- generation. This file was authored to match schema.prisma exactly; a human
-- must run `npm run prisma:migrate` (or `prisma migrate deploy`) against a
-- reachable database to apply it.

DO $$
BEGIN
    CREATE TYPE "MeetingStatus" AS ENUM ('UPLOADING', 'PROCESSING', 'READY', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE "AudioChunkStatus" AS ENUM ('PENDING', 'UPLOADED', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE "ActionItemStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'DONE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "meetings" (
    "id" TEXT NOT NULL,
    "ownerEmail" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "status" "MeetingStatus" NOT NULL DEFAULT 'UPLOADING',
    "audioUrl" TEXT,
    "durationSec" INTEGER,
    "fileSizeBytes" INTEGER,
    "mimeType" TEXT,
    "failureReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "meetings_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "meetings_ownerEmail_createdAt_idx" ON "meetings"("ownerEmail", "createdAt");

CREATE TABLE IF NOT EXISTS "meeting_audio_chunks" (
    "id" TEXT NOT NULL,
    "meetingId" TEXT NOT NULL,
    "sequence" INTEGER NOT NULL,
    "storageUrl" TEXT,
    "durationSec" INTEGER,
    "sizeBytes" INTEGER,
    "status" "AudioChunkStatus" NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meeting_audio_chunks_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "meeting_audio_chunks_meetingId_sequence_key" ON "meeting_audio_chunks"("meetingId", "sequence");
CREATE INDEX IF NOT EXISTS "meeting_audio_chunks_meetingId_idx" ON "meeting_audio_chunks"("meetingId");

CREATE TABLE IF NOT EXISTS "meeting_speakers" (
    "id" TEXT NOT NULL,
    "meetingId" TEXT NOT NULL,
    "speakerKey" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meeting_speakers_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "meeting_speakers_meetingId_speakerKey_key" ON "meeting_speakers"("meetingId", "speakerKey");
CREATE INDEX IF NOT EXISTS "meeting_speakers_meetingId_idx" ON "meeting_speakers"("meetingId");

CREATE TABLE IF NOT EXISTS "meeting_speaker_mappings" (
    "id" TEXT NOT NULL,
    "meetingId" TEXT NOT NULL,
    "speakerKey" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "updatedByEmail" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "meeting_speaker_mappings_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "meeting_speaker_mappings_meetingId_speakerKey_key" ON "meeting_speaker_mappings"("meetingId", "speakerKey");
CREATE INDEX IF NOT EXISTS "meeting_speaker_mappings_meetingId_idx" ON "meeting_speaker_mappings"("meetingId");

CREATE TABLE IF NOT EXISTS "meeting_transcript_segments" (
    "id" TEXT NOT NULL,
    "meetingId" TEXT NOT NULL,
    "speakerKey" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    "startTimeMs" INTEGER NOT NULL,
    "endTimeMs" INTEGER NOT NULL,
    "textEn" TEXT,
    "textVi" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meeting_transcript_segments_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "meeting_transcript_segments_meetingId_order_idx" ON "meeting_transcript_segments"("meetingId", "order");

CREATE TABLE IF NOT EXISTS "meeting_bookmarks" (
    "id" TEXT NOT NULL,
    "meetingId" TEXT NOT NULL,
    "timestampMs" INTEGER NOT NULL,
    "label" TEXT,
    "createdByEmail" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meeting_bookmarks_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "meeting_bookmarks_meetingId_timestampMs_idx" ON "meeting_bookmarks"("meetingId", "timestampMs");

CREATE TABLE IF NOT EXISTS "meeting_summaries" (
    "id" TEXT NOT NULL,
    "meetingId" TEXT NOT NULL,
    "overview" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "meeting_summaries_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "meeting_summaries_meetingId_key" ON "meeting_summaries"("meetingId");

CREATE TABLE IF NOT EXISTS "meeting_topics" (
    "id" TEXT NOT NULL,
    "summaryId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "evidenceSegmentIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meeting_topics_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "meeting_topics_summaryId_idx" ON "meeting_topics"("summaryId");

CREATE TABLE IF NOT EXISTS "meeting_decisions" (
    "id" TEXT NOT NULL,
    "summaryId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "evidenceSegmentIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "timestampMs" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meeting_decisions_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "meeting_decisions_summaryId_idx" ON "meeting_decisions"("summaryId");

CREATE TABLE IF NOT EXISTS "meeting_action_items" (
    "id" TEXT NOT NULL,
    "summaryId" TEXT NOT NULL,
    "task" TEXT NOT NULL,
    "owner" TEXT,
    "deadline" TIMESTAMP(3),
    "status" "ActionItemStatus" NOT NULL DEFAULT 'OPEN',
    "evidenceSegmentIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "startTimeMs" INTEGER,
    "endTimeMs" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "meeting_action_items_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "meeting_action_items_summaryId_idx" ON "meeting_action_items"("summaryId");

CREATE TABLE IF NOT EXISTS "meeting_blockers" (
    "id" TEXT NOT NULL,
    "summaryId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "evidenceSegmentIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "timestampMs" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meeting_blockers_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "meeting_blockers_summaryId_idx" ON "meeting_blockers"("summaryId");

CREATE TABLE IF NOT EXISTS "meeting_open_questions" (
    "id" TEXT NOT NULL,
    "summaryId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "evidenceSegmentIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "timestampMs" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meeting_open_questions_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "meeting_open_questions_summaryId_idx" ON "meeting_open_questions"("summaryId");

ALTER TABLE "meeting_audio_chunks" ADD CONSTRAINT "meeting_audio_chunks_meetingId_fkey" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_speakers" ADD CONSTRAINT "meeting_speakers_meetingId_fkey" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_speaker_mappings" ADD CONSTRAINT "meeting_speaker_mappings_meetingId_fkey" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_transcript_segments" ADD CONSTRAINT "meeting_transcript_segments_meetingId_fkey" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_bookmarks" ADD CONSTRAINT "meeting_bookmarks_meetingId_fkey" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_summaries" ADD CONSTRAINT "meeting_summaries_meetingId_fkey" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_topics" ADD CONSTRAINT "meeting_topics_summaryId_fkey" FOREIGN KEY ("summaryId") REFERENCES "meeting_summaries"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_decisions" ADD CONSTRAINT "meeting_decisions_summaryId_fkey" FOREIGN KEY ("summaryId") REFERENCES "meeting_summaries"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_action_items" ADD CONSTRAINT "meeting_action_items_summaryId_fkey" FOREIGN KEY ("summaryId") REFERENCES "meeting_summaries"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_blockers" ADD CONSTRAINT "meeting_blockers_summaryId_fkey" FOREIGN KEY ("summaryId") REFERENCES "meeting_summaries"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meeting_open_questions" ADD CONSTRAINT "meeting_open_questions_summaryId_fkey" FOREIGN KEY ("summaryId") REFERENCES "meeting_summaries"("id") ON DELETE CASCADE ON UPDATE CASCADE;
