-- Adds MeetingGroup: user-defined sidebar folders for organizing meetings
-- (MeetingAside.tsx "create group / move meeting into group"), plus the
-- optional Meeting.groupId FK.
-- Hand-written (not generated by `prisma migrate dev`) because the local dev
-- database has pre-existing, unrelated drift outside the migrations
-- directory (see 20260907120000_add_meeting_module's own note) that blocks
-- `migrate dev`'s diff/reset flow. Applied directly with
-- `prisma db execute --file ... --schema prisma/schema.prisma`, then marked
-- applied via `prisma migrate resolve --applied` so migration history stays
-- consistent without touching the unrelated drift.

CREATE TABLE IF NOT EXISTS "meeting_groups" (
    "id" TEXT NOT NULL,
    "ownerEmail" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "meeting_groups_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "meeting_groups_ownerEmail_order_idx" ON "meeting_groups"("ownerEmail", "order");

ALTER TABLE "meetings" ADD COLUMN IF NOT EXISTS "groupId" TEXT;
CREATE INDEX IF NOT EXISTS "meetings_groupId_idx" ON "meetings"("groupId");

DO $$
BEGIN
    ALTER TABLE "meetings" ADD CONSTRAINT "meetings_groupId_fkey"
        FOREIGN KEY ("groupId") REFERENCES "meeting_groups"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
